- name: Playbook1
  hosts: all
  vars:
    URL: www.google.com
    URL_i: www.google.com/images
  tasks:
    - ping:
    - shell: uptime >> demo.txt
    - name: Print messages
      debug:
        msg:
          welcome to cloudblitz
          my name is swapnil
